### ISSUE TITLE
A failed deploy can leave a release behind, effectively clearing the PR history

### ISSUE THREAD

**Issue by balvig** [balvig/capistrano-fiesta#4]
Is there a way to figure out what the `current` symlink is pointing to?

**Comment by Knack** [comment]
Maybe [File.readlink](http://ruby-doc.org/core-2.2.3/File.html#method-c-readlink)?

**Comment by Knack** [comment]
there's a command [readlink](http://linux.die.net/man/1/readlink) in GNU coreutils, most if not all distros should have it

**Comment by balvig** [comment]
Good idea, thanks! Will try it out tomorrow #5 :smile:
